In [1]:
import pandas as pd
import numpy as np

In [3]:
prices_per_category = pd.Series({"Product A" : 10000, "Product B" : 12000, "Product C" : 17000})
prices_per_category

Product A    10000
Product B    12000
Product C    17000
dtype: int64

In [5]:
prices_per_category.values

array([10000, 12000, 17000], dtype=int64)

In [6]:
type(prices_per_category.values)

numpy.ndarray

In [9]:
prices_per_category.array

<PandasArray>
[10000, 12000, 17000]
Length: 3, dtype: int64

In [10]:
type(prices_per_category.array)

pandas.core.arrays.numpy_.PandasArray

In [26]:
prices_per_category.to_numpy()

array([10000, 12000, 17000], dtype=int64)

In [14]:
type(prices_per_category.to_numpy())

numpy.ndarray

In [15]:
test_array = prices_per_category[["Product A", "Product B"]].to_numpy(dtype='float')
test_array

array([10000., 12000.])

In [16]:
type(test_array[0])

numpy.float64

In [18]:
prices_per_category.values[0]

10000

In [19]:
type(prices_per_category.values[0])

numpy.int64

In [20]:
prices_per_category.array[0]

10000

In [21]:
type(prices_per_category.array[0])

numpy.int64

In [23]:
prices_per_category.to_numpy()[0]

10000

In [24]:
type(prices_per_category.to_numpy()[0])

numpy.int64